name: flutter_starter_kit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  # Core Flutter & UI Packages
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_hooks: ^0.20.5
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.17

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Networking & HTTP
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Utilities & Helpers
  dartz: ^0.10.1
  go_router: ^14.6.3
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.2.1
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2
  open_filex: ^4.6.0
  image_picker: ^1.1.2
  recaptcha_enterprise_flutter: ^18.6.1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1

  intl: ^0.19.0
  meta: ^1.15.0 
  mockito: ^5.4.5
  mocktail: ^1.0.4
  bloc_test: ^10.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  injectable_generator: ^2.7.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/.env/



